function Floe = initialize_floe_values(poly1)
rho_ice=920;
poly1 = translate(poly1, [(-1)^randi([0 1])*rand (-1)^randi([0 1])*rand]);
%h = 0.2*rand+0.1128;
h=1;
[Xi,Yi] = centroid(poly1);
    Floe.area = area(poly1);
    Floe.mass = Floe.area*h*rho_ice;
    Floe.inertia_moment = PolygonMoments(poly1.Vertices,h);
    Floe.rmax = sqrt(max(sum((poly1.Vertices' - [Xi;Yi]).^2,1)));
    Floe.Xi = Xi;
    Floe.Yi = Yi;
    Floe.alpha_i = 0;
    Floe.Ui = 0;
    Floe.Vi = 0;
    Floe.ksi_ice = 0;
    Floe.alive = 1;
    Floe.dXi_p = 0;
    Floe.dYi_p = 0;
    Floe.dUi_p = 0;
    Floe.dVi_p = 0;
    Floe.dalpha_i_p = 0;
    Floe.dksi_ice_p = 0;
    Floe.collision_force = 0;
    Floe.collision_torque = 0;
    Floe.poly = poly1;
    Floe.h = h;
    Floe.E = 1e9;
    Floe.sigma_m = 400000;
    Floe.interactions = [];
    Floe.OverlapArea = 0;
    Floe.potentialInteractions = [];

end